## Server
server:
  port: 9000

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/ums?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: passw

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000  # 15 Minutes
  refresh-token-expiration: 604800000 # 7 Days

frontend:
  url: ${FRONTEND_URL}
  success-redirect: ${AUTH_SUCCESS_PATH}
  failure-redirect: ${AUTH_FAIL_PATH}